import LambdaS.Fundamental

/-!
# Non-definability: why `root` must be primitive

`root` is a primitive constructor of Λs. The justification has been an
argument in prose: from an argument at `u²` and literals at `1`, closure under
`+ − × ÷` reaches exactly the subgroup generated by `u²`, and `u` is not in it.
This file makes that a theorem.

## Why the fundamental theorem is not enough

Applying `scaleLaw` to a hypothetical term of type `Q (u·u) → Q u` gives
`f(k²x) = k·f(x)` for every `k > 0`, hence `f(y) = √y · f(1)`. So parametricity
says any such function **is** square root — it does not say none exists. That is
exactly why Kennedy needs a strengthening for his semantic proof: *"a more
generous notion of scaling environment (homomorphisms from subgroups of Unt)"*.

## The shortcut

Λs has no `if` and no `rec`, so for the arithmetic fragment a *syntactic*
argument suffices and gives a stronger conclusion: the fragment's type is
**uninhabited**, not merely uncomputable.

The key observation is that `mul` and `div` add and subtract exponent vectors,
so the reachable units form the **ℤ**-span of the arguments' units — not the
ℚ-span. Over ℚ we would have `u = (u²)^(1/2)` and the argument would collapse;
over ℤ, `u ∉ {u^(2n)}`. The distinction between what the *unit algebra* permits
and what the *term grammar* can build is the whole content, and it is why roots
have to be given rather than derived.
-/

namespace LambdaS.NonDef

open LambdaS

variable {B : Type} {k : ℕ}

/-! ## Rational powers of a single unit -/

theorem rpow_zero (w : UExp B k) : Term.rpow w 0 = 1 := by
  refine Term.ext' (funext fun x => ?_) (funext fun x => ?_) <;> simp

theorem rpow_one (w : UExp B k) : Term.rpow w 1 = w := by
  refine Term.ext' (funext fun x => ?_) (funext fun x => ?_) <;> simp

theorem rpow_add (w : UExp B k) (a b : ℚ) :
    Term.mul (Term.rpow w a) (Term.rpow w b) = Term.rpow w (a + b) := by
  refine Term.ext' (funext fun x => ?_) (funext fun x => ?_) <;> simp <;> ring

theorem rpow_sub (w : UExp B k) (a b : ℚ) :
    Term.div (Term.rpow w a) (Term.rpow w b) = Term.rpow w (a - b) := by
  refine Term.ext' (funext fun x => ?_) (funext fun x => ?_) <;> simp <;> ring

/-! ## The reachable units

`InSpan S u` says `u` can be built from the units in `S` using exactly the
operations the term grammar provides: the trivial unit (from a literal), the
generators (from variables), and multiplication and division. -/

/-- The units reachable from `S` by the operations of the arithmetic fragment. -/
inductive InSpan (S : List (UExp B k)) : UExp B k → Prop where
  /-- A literal contributes the trivial unit. -/
  | one : InSpan S 1
  /-- A variable contributes its own unit. -/
  | gen {u} : u ∈ S → InSpan S u
  | mul {u v} : InSpan S u → InSpan S v → InSpan S (Term.mul u v)
  | div {u v} : InSpan S u → InSpan S v → InSpan S (Term.div u v)

/-- From a single generator, the reachable units are exactly its **integer**
powers. This is where `mul`/`div` being addition and subtraction of exponents —
rather than arbitrary ℚ-scaling — does its work. -/
theorem inSpan_single {w v : UExp B k} (h : InSpan [w] v) :
    ∃ n : ℤ, v = Term.rpow w (n : ℚ) := by
  induction h with
  | one => exact ⟨0, by simpa using (rpow_zero w).symm⟩
  | gen hmem =>
    rw [List.mem_singleton] at hmem
    exact ⟨1, by simpa [hmem] using (rpow_one w).symm⟩
  | mul _ _ ih1 ih2 =>
    obtain ⟨a, ha⟩ := ih1
    obtain ⟨b, hb⟩ := ih2
    exact ⟨a + b, by rw [ha, hb, rpow_add]; norm_cast⟩
  | div _ _ ih1 ih2 =>
    obtain ⟨a, ha⟩ := ih1
    obtain ⟨b, hb⟩ := ih2
    exact ⟨a - b, by rw [ha, hb, rpow_sub]; norm_cast⟩

/-- **The square root of a unit is unreachable.**

If `u` is nontrivial, then `u` is not in the span of `u²`: it would have to be
`u^(2n)` for an integer `n`, forcing `1 = 2n` in ℚ. -/
theorem not_inSpan_sq {u : UExp B k} {b : B} (hb : u.base b ≠ 0) :
    ¬ InSpan [Term.mul u u] u := by
  intro h
  obtain ⟨n, hn⟩ := inSpan_single h
  have hbase : u.base b = (n : ℚ) * (u.base b + u.base b) := by
    have := congrArg (fun t => Term.base t b) hn
    simpa using this
  have h2 : ((2 * n : ℤ) : ℚ) = 1 := by
    field_simp at hbase
    push_cast
    nlinarith [hbase, sq_nonneg (u.base b)]
  have : (2 * n) = 1 := by exact_mod_cast h2
  omega

/-! ## The arithmetic fragment, intrinsically typed by its unit -/

/-- Expressions of the arithmetic fragment over a context of scalar units,
indexed by the unit of their result: literals, variables, and the field
operations. -/
inductive Arith (S : List (UExp B k)) : UExp B k → Type where
  | var {u} : u ∈ S → Arith S u
  | lit : ℚ → Arith S 1
  | mul {u v} : Arith S u → Arith S v → Arith S (Term.mul u v)
  | div {u v} : Arith S u → Arith S v → Arith S (Term.div u v)
  | add {u} : Arith S u → Arith S u → Arith S u

/-- Every unit an arithmetic expression can have is reachable from its context. -/
theorem arith_inSpan {S : List (UExp B k)} {u : UExp B k} (e : Arith S u) :
    InSpan S u := by
  induction e with
  | var h => exact .gen h
  | lit _ => exact .one
  | mul _ _ ih1 ih2 => exact .mul ih1 ih2
  | div _ _ ih1 ih2 => exact .div ih1 ih2
  | add _ _ ih1 _ => exact ih1

/-- **Square root is not definable.**

Given only a quantity of unit `u²`, no arithmetic expression has unit `u`. The
type is *uninhabited* — not merely hard to reach, and not merely uncomputable.

So `root` is not a convenience: without it the field operations cannot express
the square root of a dimensioned quantity at all — no expression they build even
has the right unit. (For full Λs the syntactic claim needs the caveat that
`ucon` inhabits `Q u` in any context, so the *type* is inhabited; what this
result pins down is that arithmetic alone never reaches the unit.) Together with
the admissibility criterion — a primitive may take any type whose denotation is
scale-invariant, and `√` is — this says `root` is both **necessary** and
**permitted**. -/
theorem sqrt_not_definable {u : UExp B k} {b : B} (hb : u.base b ≠ 0) :
    IsEmpty (Arith [Term.mul u u] u) :=
  ⟨fun e => not_inSpan_sq hb (arith_inSpan e)⟩

/-- The same statement for Newton's iteration, which is where the intuition
usually goes. The iteration itself is well-typed — `(x + a/x)/2` has unit `u`
whenever `x` does — but no *seed* of unit `u` exists to start it, so the whole
construction is unavailable. Kennedy's Exercise 14 hint in miniature. -/
theorem no_newton_seed {u : UExp B k} {b : B} (hb : u.base b ≠ 0) :
    ¬ Nonempty (Arith [Term.mul u u] u) := by
  rw [← not_isEmpty_iff]
  simp [sqrt_not_definable hb]

/-! ## Conversion is not definable either

The results above concern `sqrt`, and there they are weaker than the literature:
Atkey, Johann and Kennedy (POPL'13, Examples 6 and 8) prove non-definability of
square root semantically, in Coq, and go further — cube root stays undefinable
even if square root is added as a primitive.

This section proves something their framework cannot state, because their
calculus has no operation that reads a unit: **`convert` is a genuine
primitive**. Any parametric, convert-free function from `Q u` to `Q v` is
constantly zero whenever some scaling separates `u` from `v` — parametricity
matters, since `λx. (x / ucon u) · ucon v` is convert-free and denotes the
identity at that type. So conversion is not a derived
operation dressed up as a constructor, and the coherence hypothesis on
`fundamental` is not the price of a redundant feature.

The proof is the semantic one — apply `fundamental_free` at a scaling that
fixes `u` and moves `v` — which is exactly AJK's technique, used on a question
that only arises once conversion exists. -/

section ConvertPrimitive

open scoped BigOperators

variable {B D : Type} [Fintype B] [DecidableEq B] [Fintype D] [UnitSys B D] {j k : ℕ}
variable {Δ : DCtx D j k}

/-- The scale factor of a bare generator is the exponential of its entry. -/
theorem scale_ofBase (ψ : Scaling B k) (b : B) :
    ψ.scale (Term.ofBase b) = Real.exp (ψ.base b) := by
  simp only [Scaling.scale, Scaling.logScale, Term.ofBase]
  congr 1
  rw [Finset.sum_eq_single b] <;> simp_all

/-- A scaling that fixes one generator and doubles another. Two base units of the
same dimension are separated by such a scaling, which is exactly the freedom
`Scaling.Coherent` forbids — and the freedom that makes conversion observable. -/
noncomputable def separate (b c : B) : Scaling B k :=
  ⟨fun b' => if b' = c then Real.log 2 else 0, fun _ => 0⟩

theorem separate_fixes {b c : B} (h : b ≠ c) : (separate (k := k) b c).scale (Term.ofBase b) = 1 := by
  rw [scale_ofBase]; simp [separate, h]

theorem separate_moves (b c : B) : (separate (k := k) b c).scale (Term.ofBase c) = 2 := by
  rw [scale_ofBase]; simp [separate, Real.exp_log]

/-- **Conversion cannot be simulated.** A convert-free function from `Q u` to
`Q v` is the zero function, as soon as one scaling fixes `u` and moves `v`.

This is the statement `fundamental_free` was built to make: no coherence
hypothesis, so `ψ` may be chosen adversarially, and the adversarial choice
collapses the function. -/
theorem convertFree_eq_zero {u v : UExp B k} {e : Tm B D j k}
    (d : HasTy Δ ([] : Ctx B D j k) e (.arrow (.Q u) (.Q v)))
    (hp : e.Parametric) (hf : e.ConvertFree)
    (V : Scaling B k) {ψ : Scaling B k} (h1 : ψ.scale u = 1) (h2 : ψ.scale v ≠ 1)
    (x : ℝ) : den V d PUnit.unit x = 0 := by
  have hrel := fundamental_free d hp hf V ψ (ρ := PUnit.unit) (ρ' := PUnit.unit) trivial
  have hx : den (V.comp ψ) d PUnit.unit (ψ.scale u * x)
      = ψ.scale v * den V d PUnit.unit x := hrel x (ψ.scale u * x) rfl
  rw [h1, one_mul, den_indep d hf (V.comp ψ) V trivial x x rfl] at hx
  have : (1 - ψ.scale v) * den V d PUnit.unit x = 0 := by linarith [hx]
  rcases mul_eq_zero.mp this with h | h
  · exact absurd (by linarith [h] : ψ.scale v = 1) h2
  · exact h

/-- **So `convert` is primitive.** No convert-free term denotes conversion
between two distinct base units, because conversion is multiplication by a
positive factor and the only convert-free candidate is zero.

Together with `fundamental` this is the design claim, proved in both
directions: conversion cannot be removed from the language, and keeping it costs
exactly coherence. -/
theorem convert_not_definable {b c : B} (hbc : b ≠ c) (V : Scaling B k)
    {e : Tm B D j k} (d : HasTy Δ ([] : Ctx B D j k) e
      (.arrow (.Q (Term.ofBase b)) (.Q (Term.ofBase c))))
    (hp : e.Parametric) (hf : e.ConvertFree) :
    den V d PUnit.unit 1 ≠ 1 * conv V (Term.ofBase b) (Term.ofBase c) := by
  rw [convertFree_eq_zero d hp hf V (ψ := separate b c)
        (separate_fixes hbc) (by rw [separate_moves]; norm_num) 1]
  simpa using (ne_of_gt (conv_pos V (Term.ofBase b) (Term.ofBase c))).symm

end ConvertPrimitive

end LambdaS.NonDef
